modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="tp"
version="4.1.2"
displayName="deltarune TP"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="u/nnilo001 on reddit"
description="deltarune TP bar in minecraft!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.tp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration